### ISSUE TITLE
Fallo al compilar

### ISSUE THREAD

**Issue by fermintm** [enlinea777/enlinea777-u8g2_suport_ESP8266#1]
U8G2_SSD1327_EA_W128128_F_HW_I2C u8g2_P(U8G2_R0,U8X8_PIN_NONE,D1,D2); da error al compilar. Hay que eliminar _P para que pueda hacerlo.

**Comment by enlinea777** [comment]
u8g2_P es un nombre de referencia puede ser:
U8G2_SSD1327_EA_W128128_F_HW_I2C u8g2_cualquier_cosa(U8G2_R0,U8X8_PIN_NONE,D1,D2);
y debes usarlo asi:

u8g2_cualquier_cosa.begin();

y todas las llamadas a la clase u8g2_cualquier_cosa

**Comment by fermintm** [comment]
Gracias por la info.
Saludos
